name: cupid-dev
dependencies:
    - python=3.11.4
    - black
    - click
    - dask
    - dask-jobqueue
    - intake
    - intake-esm
    - jinja2
    - jupyter-book
    - nco
    - pandas
    - papermill
    - pip
    - ploomber=0.22.3
    - pyyaml
    - xarray
    - pip:
      - -e ../
